pipeline { 
    agent {
        kubernetes {
            label 'test-app'  // all your pods will be named with this prefix, followed by a unique id
            idleMinutes 5  // how long the pod will live after no jobs have run on it
            yamlFile 'build.yaml'  // path to the pod definition relative to the root of our project 
            defaultContainer 'maven'  // define a default container if more than a few stages use it, will default to jnlp container
        }
    }
    
    options {
        // set a timeout of 20 minutes for this pipeline
        timeout(time: 40, unit: 'MINUTES')
    }
    stages { 
        stage('Checkout SCM & Initialize') {
            steps {
                script {
                    checkout scm: scm

                }
            }
        }
        stage('Build') { 
            steps { 
               sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Tests') {
            steps {
                // Report back to github: Status Check PENDING
                //notifyGithubStatusCheck('PENDING', 'Continuous integration: Run unit test!')

                sh "mvn test"
                //step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
            } 
        }
    }
}