pipeline { 
    agent {
        label 'maven'
    }
    
    options {
        // set a timeout of 20 minutes for this pipeline
        timeout(time: 40, unit: 'MINUTES')
    }
    stages { 
        stage('Checkout SCM & Initialize') {
            steps {
                script {
                    checkout scm: scm

                }
            }
        }
        stage('Build') { 
            steps { 
               sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Tests') {
            steps {
                // Report back to github: Status Check PENDING
                //notifyGithubStatusCheck('PENDING', 'Continuous integration: Run unit test!')

                sh "mvn test -f ${POM_FILE}"
                //step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
            } 
        }
    }
}